In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
weather = pd.read_csv(r'weather.csv', index_col=0) # index_col=0:第一列为索引值

In [3]:
weather.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,24.0,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,22.0,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,20.0,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No

In [6]:
# 将特征矩阵和标签分开
X = weather.iloc[:, :-1]
Y = weather.iloc[:, -1]

In [7]:
X.shape

(142193, 21)

In [8]:
Y.shape

(142193,)

In [9]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142193 entries, 0 to 142192
Data columns (total 21 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           142193 non-null  object
 1   Location       142193 non-null  object
 2   MinTemp        141556 non-null  float64
 3   MaxTemp        141871 non-null  float64
 4   Rainfall       140787 non-null  float64
 5   Evaporation    81350 non-null   float64
 6   Sunshine       74377 non-null   float64
 7   WindGustDir    132863 non-null  object
 8   WindGustSpeed  132923 non-null  float64
 9   WindDir9am     132180 non-null  object
 10  WindDir3pm     138415 non-null  object
 11  WindSpeed9am   140845 non-null  float64
 12  WindSpeed3pm   139563 non-null  float64
 13  Humidity9am    140419 non-null  float64
 14  Humidity3pm    138583 non-null  float64
 15  Pressure9am    128179 non-null  float64
 16  Pressure3pm    128212 non-null  float64
 17  Cloud9am       88536 non-null   float64
 18  Cloud3pm       85099 non-null   float64
 19  Temp9am        141289 non-null  float64
 20  Temp3pm        139467 non-null  float64
dtypes: float64(16), object(5)
memory usage: 23.9+ MB

In [21]:
X.isnull().mean() # 缺失值

Date             0.000000
Location         0.000000
MinTemp          0.004480
MaxTemp          0.002265
Rainfall         0.009888
Evaporation      0.427890
Sunshine         0.476929
WindGustDir      0.065615
WindGustSpeed    0.065193
WindDir9am       0.070418
WindDir3pm       0.026570
WindSpeed9am     0.009480
WindSpeed3pm     0.018496
Humidity9am      0.012476
Humidity3pm      0.025388
Pressure9am      0.098556
Pressure3pm      0.098324
Cloud9am         0.377353
Cloud3pm         0.401525
Temp9am          0.006358
Temp3pm          0.019171
dtype: float64

In [22]:
Y.isnull().mean()

0.0

In [11]:
np.unique(Y) # 探索标签的分类

array(['No', 'Yes'], dtype=object)

In [12]:
# 将数据分为训练集和测试集
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size=0.3, random_state=420)
for i in [Xtrain, Xtest, Ytrain, Ytest]: # 恢复索引
    i.index = range(i.shape[0])

In [16]:
# 样本不平衡问题探索
Ytrain.value_counts()

No     77238
Yes    22297
Name: RainTomorrow, dtype: int64

In [17]:
Ytest.value_counts()

No     33078
Yes     9580
Name: RainTomorrow, dtype: int64

In [18]:
# 将标签进行编码
from sklearn.preprocessing import LabelEncoder
encorder = LabelEncoder().fit(Ytrain) 
Ytrain = pd.DataFrame(encorder.transform(Ytrain))
Ytest = pd.DataFrame(encorder.transform(Ytest))

In [19]:
np.unique(Ytrain)

array([0, 1])

In [20]:
np.unique(Ytest)

array([0, 1])

In [25]:
# 描述性统计与异常值
Xtrain.describe([0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,99%,max
MinTemp,99092.0,12.179886,6.404463,-8.5,-1.809,1.8,3.9,7.6,12.0,16.8,20.8,25.800,31.9
MaxTemp,99292.0,23.212779,7.110535,-4.1,9.100,12.8,14.5,17.9,22.6,28.2,32.9,40.100,48.1
Rainfall,98535.0,2.348739,8.438048,0.0,0.000,0.0,0.0,0.0,0.0,0.6,6.0,37.400,367.6
Evaporation,56898.0,5.455923,4.164123,0.0,0.400,1.0,1.4,2.6,4.8,7.4,10.2,18.206,86.2
Sunshine,51968.0,7.609452,3.782961,0.0,0.000,0.3,1.5,4.8,8.4,10.6,12.0,13.400,14.3
WindGustSpeed,93045.0,39.988285,13.624007,6.0,15.000,20.0,24.0,31.0,39.0,48.0,57.0,81.000,135.0
WindSpeed9am,98591.0,14.006319,8.922327,0.0,0.000,0.0,4.0,7.0,13.0,19.0,26.0,39.000,130.0
WindSpeed3pm,97698.0,18.633841,8.814635,0.0,2.000,6.0,9.0,13.0,19.0,24.0,30.0,43.000,83.0
Humidity9am,98284.0,68.845265,19.074180,0.0,17.000,34.0,44.0,57.0,70.0,83.0,94.0,100.000,100.0
Humidity3pm,96953.0,51.497798,20.776461,0.0,9.000,17.0,23.0,37.0,52.0,66.0,79.0,98.000,100.0
Pressure9am,89710.0,1017.649291,7.106287,980.5,1000.209,1006.2,1008.8,1012.9,1017.6,1022.4,1026.7,1034.000,1041.0
Pressure3pm,89732.0,1015.254827,7.031155,977.1,998.600,1004.0,1006.4,1010.4,1015.2,1020.0,1024.3,1031.600,1038.9
Cloud9am,61926.0,4.442367,2.886461,0.0,0.000,0.0,1.0,1.0,5.0,7.0,8.0,8.000,9.0
Cloud3pm,59453.0,4.512052,2.717039,0.0,0.000,0.0,1.0,2.0,5.0,7.0,8.0,8.000,8.0
Temp9am,98927.0,16.977519,6.491470,-7.0,2.600,6.9,8.9,12.3,16.7,21.6,25.9,31.200,39.4
Temp3pm,97607.0,21.675382,6.929835,-5.1,7.700,11.5,13.2,16.6,21.1,26.4,31.2,38.400,46.7

In [26]:
Xtest.describe([0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,99%,max
MinTemp,42464.0,12.201599,6.400577,-7.6,-1.8,1.8,4.0,7.6,12.0,16.9,20.8,25.800,33.9
MaxTemp,42579.0,23.259442,7.134084,-4.8,9.0,12.8,14.5,18.0,22.7,28.2,33.0,40.300,47.0
Rainfall,42252.0,2.352854,8.528195,0.0,0.0,0.0,0.0,0.0,0.0,0.8,6.0,37.498,371.0
Evaporation,24452.0,5.502172,4.244710,0.0,0.4,1.0,1.4,2.6,4.8,7.4,10.2,18.600,145.0
Sunshine,22409.0,7.660569,3.778036,0.0,0.0,0.4,1.6,4.9,8.5,10.7,12.1,13.400,14.5
WindGustSpeed,39878.0,39.974974,13.506464,7.0,15.0,20.0,24.0,31.0,39.0,48.0,57.0,80.000,135.0
WindSpeed9am,42254.0,13.991882,8.825421,0.0,0.0,0.0,4.0,7.0,13.0,19.0,26.0,39.000,87.0
WindSpeed3pm,41865.0,18.646292,8.777042,0.0,2.0,6.0,9.0,13.0,19.0,24.0,30.0,43.000,87.0
Humidity9am,42135.0,68.840418,18.998023,3.0,18.0,34.0,44.0,57.0,70.0,83.0,94.0,100.000,100.0
Humidity3pm,41630.0,51.447226,20.847527,1.0,9.0,16.0,23.0,36.0,52.0,66.0,79.0,97.000,100.0
Pressure9am,38469.0,1017.664176,7.103665,982.2,1000.2,1006.2,1008.8,1013.0,1017.7,1022.4,1026.8,1034.000,1040.5
Pressure3pm,38480.0,1015.266077,7.049621,978.2,998.4,1004.0,1006.5,1010.4,1015.3,1020.0,1024.3,1031.700,1039.6
Cloud9am,26610.0,4.425141,2.888324,0.0,0.0,0.0,1.0,1.0,5.0,7.0,8.0,8.000,9.0
Cloud3pm,25646.0,4.482570,2.728886,0.0,0.0,0.0,1.0,2.0,5.0,7.0,8.0,8.000,9.0
Temp9am,42362.0,17.010838,6.496049,-7.2,2.6,7.0,8.9,12.3,16.7,21.6,25.9,31.300,40.2
Temp3pm,41860.0,21.714873,6.955656,-5.4,7.6,11.5,13.2,16.6,21.2,26.4,31.3,38.600,45.2

In [34]:
Xtrain.shape

(99535, 21)

In [28]:
Ytrain.shape

(99535, 1)

In [35]:
# 处理日期特征
Xtrainc = Xtrain.copy()

In [37]:
Xtrainc.sort_values(by='Location')

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
97360,2011-03-31,Adelaide,10.8,20.3,0.0,3.6,10.7,E,28.0,NaN,...,0.0,9.0,64.0,38.0,1029.7,1026.2,NaN,NaN,12.8,19.8
25605,2012-11-07,Adelaide,12.8,23.3,0.2,5.0,NaN,WNW,44.0,NW,...,9.0,20.0,64.0,38.0,1012.5,1011.2,NaN,NaN,16.7,22.3
31948,2015-04-03,Adelaide,12.1,23.0,0.0,NaN,NaN,ESE,52.0,E,...,15.0,9.0,46.0,24.0,1024.2,1020.5,NaN,NaN,13.1,22.6
11800,2012-10-15,Adelaide,16.2,27.6,0.0,15.2,NaN,N,37.0,N,...,9.0,15.0,60.0,24.0,1018.3,1016.7,NaN,NaN,18.6,26.7
92946,2013-10-14,Adelaide,9.3,17.4,2.0,13.8,7.0,W,37.0,SSW,...,7.0,19.0,74.0,39.0,1026.1,1025.4,NaN,NaN,11.8,16.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92369,2015-06-06,Woomera,6.6,20.2,0.0,6.6,9.0,NNE,31.0,NE,...,11.0,17.0,65.0,39.0,1030.1,1026.3,0.0,0.0,12.7,19.4
90023,2013-12-24,Woomera,16.1,28.0,0.0,15.6,5.1,SSE,44.0,SE,...,20.0,13.0,48.0,29.0,1018.0,1015.2,7.0,7.0,18.6,26.4
83230,2016-03-31,Woomera,12.6,27.2,0.0,9.4,10.4,SW,28.0,ESE,...,15.0,9.0,61.0,21.0,1021.3,1017.8,0.0,NaN,15.7,25.3
4512,2011-09-09,Woomera,6.7,19.3,0.2,6.8,10.7,S,56.0,SSW,...,33.0,35.0,68.0,29.0,1028.2,1026.0,0.0,3.0,11.2,18.3
96518,2011-10-03,Woomera,7.5,26.2,0.0,4.6,9.3,NE,50.0,ENE,...,13.0,31.0,24.0,10.0,1018.9,1015.1,0.0,0.0,15.9,25.2

In [39]:
Xtrainc.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
0,2015-05-08,Uluru,8.9,23.2,0.0,NaN,NaN,E,46.0,E,...,26.0,19.0,52.0,27.0,1025.0,1020.7,NaN,NaN,14.4,21.8
1,2016-10-16,Walpole,8.8,15.0,4.4,NaN,NaN,WNW,35.0,W,...,15.0,19.0,66.0,71.0,1024.5,1023.4,NaN,NaN,13.5,13.8
2,2013-12-06,Cobar,8.1,23.6,0.0,10.0,NaN,WSW,48.0,S,...,17.0,19.0,35.0,15.0,1017.4,1016.3,0.0,0.0,14.4,21.9
3,2011-01-24,SalmonGums,15.7,26.7,3.0,NaN,NaN,S,52.0,ENE,...,19.0,33.0,77.0,63.0,NaN,NaN,NaN,NaN,19.4,22.5
4,2013-03-28,Mildura,15.3,23.9,10.4,9.6,6.1,SW,41.0,W,...,6.0,22.0,93.0,40.0,1019.5,1019.5,8.0,7.0,16.2,21.2